FROM openjdk:11-jdk-slim

WORKDIR /app

# Copy Maven wrapper & pom.xml
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline -B || true

COPY . .

EXPOSE 8070

CMD ["./mvnw", "spring-boot:run"]
