version: '3.8'

services:
  frontend:
    build:
      context: ./mypro3
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_PROXY_URL=http://backend:8070
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./ProjectSMHRD
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    ports:
      - "8070:8070"
    env_file:
      - .env.dev
    restart: always
